[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-audit --no-fund"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 5173
